### ISSUE TITLE
Font Mapping Task

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#10]

**Comment by granthleslie** [comment]
I have shared the folder with all the fonts from your email included in that folder on Dropbox.  Let me know if that doesn't do the trick.

**Comment by cindysamco** [comment]
This appears to be complete as of Build 29. However, not all card payloads have an assigned font and will be assigned Meghan. Grant, please close this ticket if your satisfied that this task is complete.

**Comment by granthleslie** [comment]
Looks like this is working!

**Comment by cindysamco** [comment]
Per Grant's approval this ticket is now closed
