### ISSUE TITLE
Rendered image on server has wrong x/y offsets

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#15]
![image](https://cloud.githubusercontent.com/assets/6485279/10976010/fb53e0f0-83a6-11e5-9977-9f015cede91c.png)

![image](https://cloud.githubusercontent.com/assets/6485279/10976016/01d9b9ae-83a7-11e5-98f2-527e6a71eda1.png)

**Comment by granthleslie** [comment]
![img_3519](https://cloud.githubusercontent.com/assets/14889785/11188567/2195bc9a-8c51-11e5-86ec-ec9c6b9f6540.PNG)
^ photo from the card on the app ^

![642](https://cloud.githubusercontent.com/assets/14889785/11188568/21a18d5e-8c51-11e5-805e-38957cabda4b.jpg)
^ photo from the card as it's generated ^

![641](https://cloud.githubusercontent.com/assets/14889785/11188586/4708df7a-8c51-11e5-8979-54d44749a7c0.jpg)
^ photo from a card as it's generated (image was centered in the image area) ^

**Comment by cindysamco** [comment]
Grant ... if a bug is open and not marked as fixed is still an open issue. It is still routed to Eric. It will be routed to you to confirm once the fixes are in place.

**Comment by cindysamco** [comment]
This appears to be working correctly in build 40. Grant, please close this bug when you are satisfied that this ticket is addressed.

**Comment by granthleslie** [comment]
Looks like this is working, too!  Whoot.

**Comment by cindysamco** [comment]
Per Grant's approval this ticket is now closed
