### ISSUE TITLE
Account Screen: Better Support for incomplete profile

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#20]
A new account doesn't have all the elements filled in yet. 
When I go to Account Screen there are labels with with no data. We should either hide those incomplete elements or prompt to complete the information.

Not sure which ... should discuss

**Comment by ericsellry** [comment]
I've added "none supplied" if the address is blank

**Comment by cindysamco** [comment]
Gender is being set to Female on new account.

**Comment by ericsellry** [comment]
blank fields will be displayed as "NOT SET"

**Comment by cindysamco** [comment]
This particular ticket is complete. There is another ticket covering what is still needed in New Account.
