### ISSUE TITLE
Account Screen: Credit Card Data should be displayed (and editable) 

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#22]
Per Photoshop File
one card only

**Comment by granthleslie** [comment]
The credit card tokenization back-port has been merged and pushed to master

**Comment by cindysamco** [comment]
Working through change order process for this one.

**Comment by ericsellry** [comment]
not sure this means anything anymore. If the current build does not do what you think it should, please open a specific ticket for the gap.

**Comment by cindysamco** [comment]
This has been implemented to being able to add a new card and choose from a list of existing cards. Closing this as done
