### ISSUE TITLE
Account / Profile screen

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#3]
granthleslie [11:10 AM]
on the app it's just user info

eric [11:11 AM] 
ok

granthleslie [11:11 AM] 
we tokenize the credit card info

granthleslie [11:11 AM]
using Spree's PaymentMethods option

**Comment by ericsellry** [comment]
don't know what this is

**Comment by cindysamco** [comment]
Closing this ticket. Getting covered in #17
