### ISSUE TITLE
Fonts from the inside page on the app are assigned incorrectly

### ISSUE THREAD

**Issue by granthleslie** [sellry/cardfool-issues#31]
This card, like all insides, should have the Meghand.ttf font used
https://staging.cardfool.com/preview_inside/472.jpg
The above is a card I created on the app ^

**Comment by ericsellry** [comment]
Please regress with the next build.

**Comment by granthleslie** [comment]
will do!  Sweet!  Thanks

**Comment by cindysamco** [comment]
please close this ticket if you are satisfied that fonts are included.

**Comment by granthleslie** [comment]
Everything seems to be working well!  excellent!
