### ISSUE TITLE
Order.line_items that are deliver_to => "Recipient" are being marked as customer orders on the back end?

### ISSUE THREAD

**Issue by granthleslie** [sellry/cardfool-issues#33]
https://staging.cardfool.com/orders/R876945161

That order on the app was sent to recipient "Sarah", but above the line_item address says 'sending to yourself', which means it's being marked as deliver_to=>"recipient"

**Comment by granthleslie** [comment]
https://staging.cardfool.com/orders/R989412838

This is another order I placed and processed, after changing some code around on the csv delivery where line_items that were delivery_to => "Recipient" and see if that works, but it still marked it as a "Shipped" order...which is weird, because the line_item record for that order says that it's deliver_to: recipient.

**Comment by cindysamco** [comment]
We need more information on this ticket:
- What is the iOS App sending that it's not supposed to?
- Is there something missing that the iOS App needs to send?

**Comment by cindysamco** [comment]
On a PRINT CARD
=> #<Spree::LineItem id: 501, variant_id: 1541, order_id: 377, quantity: 1, price: #<BigDecimal:7fa954579770,'0.399E1',18(18)>, created_at: "2015-11-10 17:52:29", updated_at: "2015-11-10 17:58:14", currency: "USD", cost_price: nil, tax_category_id: 1, adjustment_total: #<BigDecimal:7fa954573578,'0.0',9(18)>, additional_tax_total: #<BigDecimal:7fa9545733e8,'0.0',9(18)>, promo_total: #<BigDecimal:7fa9545732d0,'0.0',9(18)>, included_tax_total: #<BigDecimal:7fa9545731e0,'0.0',9(18)>, pre_tax_amount: nil, deliver_to: "recipient", shipping_date: "2015-11-10", saved_state: nil, express: false, personalized_cover: false, personalized_inside: true, source_url: nil, source_position: nil>
irb(main):036:0> l.recipient
 Recipient Load (0.7ms)  SELECT "recipients".* FROM "recipients" WHERE "recipients"."spree_line_item_id" = $1 LIMIT 1  [["spree_line_item_id", 501]]
=> nil
irb(main):037:0>

granthleslie [11:32 AM]
The line_item.recipeint is returning nil on that

**Comment by granthleslie** [comment]
The Recipients table looks like it's being populated correctly!  Excellent!

**Comment by cindysamco** [comment]
Grant confirmed this as being fixed.
