### ISSUE TITLE
Confirm Reminders are working so we can set the correct time

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#38]
Grant,

Please respond to this ticket once you're satisfied that Reminders are working (1 minute timer) for you. Then we can set the time of the reminder to be 9:00 a.m. device time.

Thanks

1. Set a reminder for 1 week or 2 weeks out
2. Switch out of the App
3. Wait a minute
Result should display a reminder

**Comment by cindysamco** [comment]
Grant ... could you please confirm that Reminders are working for you based on the steps above. I would like to get the final 9:00 a.m. change set so we can forget about this feature. Thanks!

**Comment by granthleslie** [comment]
This is working!!! EXCELLENT

**Comment by cindysamco** [comment]
Great ... I'm closing this particular ticket and will open a finalize ticket for eric.
