### ISSUE TITLE
eCard Address Screen: Improve screen to get rid of the address book icons

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#43]

**Comment by cindysamco** [comment]
Grant, This screen has been updated with build 39. Please close this ticket after reviewing the changes.

**Comment by cindysamco** [comment]
per client's request, make the buttons purple.

**Comment by cindysamco** [comment]
The next build will have purple buttons. Please close this ticket when you're satisfied.

**Comment by granthleslie** [comment]
Nice!  Thank you!!!!

**Comment by cindysamco** [comment]
Per Grant's approval this ticket is now closed
