### ISSUE TITLE
Google Analytics: Confirm ID being used

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#51]
Analytics doesn't appear to be happening.

Confirm this ID:  UA-65574101-2

**Comment by ericsellry** [comment]
was  UA-65574101-1... not sure how that happened. changed to  UA-65574101-2.

**Comment by cindysamco** [comment]
This appears to still be broken. I'm not seeing any active users in the real-time area of the analytics area. I'm thinking there's more going on here.

**Comment by cindysamco** [comment]
confirmed fixed in build 42
