### ISSUE TITLE
"Send to Me" orders are not charging the "Shipping Cost" ... the result being a balance due in the order record.

### ISSUE THREAD

**Issue by granthleslie** [sellry/cardfool-issues#55]
Sending a print card to_customer doesn't capture correctly on the back end.  You can see the "payment state" column on the backend https://staging.cardfool.com/admin/orders where it captures correctly for to_recipient and IAP orders.

**Comment by cindysamco** [comment]
Grant, I see successful and "balance due" orders. This is not us. We make the call for a card, either a new card or a saved. This is a back end issue in our opinion.

**Comment by granthleslie** [comment]
Placing a 'to_customer' order on the site works fine, so what is the difference that is causing the 'to_customer' orders on the app to be marked as 'balance due'?

**Comment by granthleslie** [comment]
Ooo!  Found it!!
# Updates the +payment_state+ attribute according to the following logic:
    #
    # paid          when +payment_total+ is equal to +total+
    # balance_due   when +payment_total+ is less than +total+
    # credit_owed   when +payment_total+ is greater than +total+
    # failed        when most recent payment is in the failed state
    #
    # The +payment_state+ value helps with reporting, etc. since it provides a quick and easy way to locate Orders needing attention.
    def update_payment_state
      last_state = order.payment_state
      if payments.present? && payments.valid.size == 0
        order.payment_state = 'failed'
      elsif order.state == 'canceled' && order.payment_total == 0
        order.payment_state = 'void'
      else
        order.payment_state = 'balance_due' if order.outstanding_balance > 0
        order.payment_state = 'credit_owed' if order.outstanding_balance < 0
        order.payment_state = 'paid' if !order.outstanding_balance?
      end
      order.state_changed('payment') if last_state != order.payment_state
      order.payment_state
    end

**Comment by cindysamco** [comment]
SUMMARY: 
When placing a "Ship to Me" orders I believe we are using the wrong Total field.
The resulting order on the backend shows a Balance Due of the shipping cost.

**Comment by granthleslie** [comment]
Has this been fixed with the correct order totals going on the credit card?

**Comment by cindysamco** [comment]
This has been addressed. You'll see that in the next build. Eric is heads down on image sizing ATM.

**Comment by cindysamco** [comment]
Build 39 appears to be doing the right thing now. Grant, please close this ticket when you are satisfied this issue is addressed.

**Comment by granthleslie** [comment]
This is looking like it works as well!

**Comment by granthleslie** [comment]
This is good!  Sweet!

**Comment by cindysamco** [comment]
Per Grant's approval, this ticket is now closed.
