### ISSUE TITLE
Profile Screen: Multiple Line Address don't fit in the space provided

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#64]
on a 6S

If Address 1 wraps and there's an Address 2, the text doesn't fit on the screen

You can truncate (...) the right side of each field IMO.
![img_6643](https://cloud.githubusercontent.com/assets/6485279/11754193/30ff03b8-a00f-11e5-967d-9838c41d161b.jpg)

**Comment by ericsellry** [comment]
made some more vertical room. also, added some more width, as that one shouldn't have wrapped.

**Comment by cindysamco** [comment]
confirmed fixed in build 43
