### ISSUE TITLE
Card Category Walk Thru

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#66]
Hey Grant,
Per our discussion on Slack, this is a generic ticket for you. You need to walk the cards and assign those that will appear in the App. Horizontal/Landscape cards need to be omitted. 
Thanks,
Cindy

Get rid of or correct the "image not found" categories: say hi and Thanksgiving

**Comment by cindysamco** [comment]
This task should also include making are all categories have a cover image. I'm going to close #65 as duplicate of this bug.

**Comment by cindysamco** [comment]
This ticket needs to be addressed _before_ we submit to the App Store for review. The horizontal cards are going to run the risk of rejection because they look so bad.

**Comment by granthleslie** [comment]
This is good, as well.  We'll continue to add inside copy and get the cards organized, but this is not in your hands at all.
