### ISSUE TITLE
Need to Timeout if network connection is lost

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#68]
Best way to repo:
1. Turn on a hotspot on a phone.
2. connect a second device and attach to hotspot
3. Launch/log in to App
4. turn off the hotspot that the App device is attached to.
5. Try and go into a category
Result: infinite spinning.

**Comment by ericsellry** [comment]
we time out at 10 seconds. That call was not handling the error correctly.

I've added a check, at the bottom of my network stack, to give the user an error if the servers are not reachable. And, I've corrected that incorrect error handling in this case.

I've added this extra checking everywhere...  I think, but maybe please regress other places which may suffer from not handling the errors correctly.

**Comment by cindysamco** [comment]
Much better in build 43.
