### ISSUE TITLE
1-week / 2-week Reminder lags implementated

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#7]

**Comment by cindysamco** [comment]
9:00 a.m.
2 weeks 
1 week

**Comment by ericsellry** [comment]
While in test, after editing any reminder, all reminders will be set to fire 1 minute from the time you do the save...  this only changes the reminder time for a reminder that was scheduled to trigger today anyway.

**Comment by cindysamco** [comment]
The testing setup for reminders appears to be working in build 29. I'll create a new ticket to set the reminder time to 9:00 a.m. device time.
