### ISSUE TITLE
eCard: Confirm Order Screen (last screen) can get munged when editing

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#71]
1. eCard
2. Advance to "Confirm Order" screen
3. Tap pencil to edit
4. Tap email field
5. Tap Save
Result: "Next button" is overplayed on other screen elements.

**Comment by ericsellry** [comment]
if it do it 5 times those elements are off the screen. :-)

**Comment by cindysamco** [comment]
confirmed fixed in build 47
