### ISSUE TITLE
Inside Card Text Support

### ISSUE THREAD

**Issue by cindysamco** [sellry/cardfool-issues#9]
Each card has an area at the bottom to show the "Inside Text" for the card. Currently it is showing a URL.

It would be great to get these populated soon. :-)

**Comment by cindysamco** [comment]
What is the status on this task? Are you going to provide "inside card text" for the string being display at the bottom of the Card Front screen?

**Comment by granthleslie** [comment]
I have added a method to the Spree::Products table called :inside_copy
You should be able to see it in the Product payload.  It defaults to " ", so if there's no actual text that's fine.  We'll be adding the copy in the coming weeks.

**Comment by granthleslie** [comment]
you can test this with the "Breathing Hard Babe" birthday card on the staging server.  There should be :inside_copy on that card

**Comment by cindysamco** [comment]
Looks like Grant set up a method to grab the inside text.

**Comment by ericsellry** [comment]
I see them, but they are all blank (including Breathing hard babe). I'm capturing this value now, and will stop putting the path to the image in as a place holder.

**Comment by granthleslie** [comment]
Ah yes...that is because I uploaded the most recent production birthday card product database, which erased the Breathing Hard Babe inside...it should be there now.  Thx!

**Comment by cindysamco** [comment]
The one card that has been updated is displaying inside text now.
